export enum RequestActionTypes {
    GET_CREDENTIAL_CREATION_OPTIONS_REQUEST = 'GET_CREDENTIAL_CREATION_OPTIONS_REQUEST',
    GET_CREDENTIAL_CREATION_OPTIONS_SUCCESS = 'GET_CREDENTIAL_CREATION_OPTIONS_SUCCESS',
    GET_CREDENTIAL_CREATION_OPTIONS_FAILURE = 'GET_CREDENTIAL_CREATION_OPTIONS_FAILURE',
    
    VALIDATE_NEW_CREDENTIAL_REQUEST = 'VALIDATE_NEW_CREDENTIAL_REQUEST',
    VALIDATE_NEW_CREDENTIAL_SUCCESS = 'VALIDATE_NEW_CREDENTIAL_SUCCESS',
    VALIDATE_NEW_CREDENTIAL_FAILURE = 'VALIDATE_NEW_CREDENTIAL_FAILURE',

    GET_ASSERTION_CREATION_OPTIONS_REQUEST = 'GET_ASSERTION_CREATION_OPTIONS_REQUEST',
    GET_ASSERTION_CREATION_OPTIONS_SUCCESS = 'GET_ASSERTION_CREATION_OPTIONS_SUCCESS',
    GET_ASSERTION_CREATION_OPTIONS_FAILURE = 'GET_ASSERTION_CREATION_OPTIONS_FAILURE',
    
    VALIDATE_NEW_ASSERTION_REQUEST = 'VALIDATE_NEW_ASSERTION_REQUEST',
    VALIDATE_NEW_ASSERTION_SUCCESS = 'VALIDATE_NEW_ASSERTION_SUCCESS',
    VALIDATE_NEW_ASSERTION_FAILURE = 'VALIDATE_NEW_ASSERTION_FAILURE',


}